language: node_js
node_js:
- '7.1'
cache:
  directories:
  - node_modules
  - "$HOME/.npm"
  - "$HOME/.gem"
before_install:
- npm install -g gulp
script:
- gulp
- gulp test
before_deploy:
- gulp
deploy:
  provider: npm
  email: me@brianneisler.com
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: YEc42U/9XtjN1UsTJZSntb9pLAQfNp080/syAcpee+k/TdCtLeYjonsjf7CTHGtHa9SgvinWJkVLtctH+mv4os93F/W0LcKb1JnGl9PydIeZkWQfqsauHRIdYyihyf5q+2bzkXz7asV+EReS3LPjuqQx31SzhipuSuLO3gou1CwPlYwQmc9m36SQOfV5acmrzJ/6nlJgCS9+ca99/078FAClgnndeM0ydEQ10q/ug8+8nxCGDbBULuH7e6s0/048lhqRNr+mZ2u+HPHEfc4FJF94rf2TcCWZFndBNJc3x57UyXP3UuMM+lnchwxo4rPfy9tD/onYSP0euaZv4xD654Yvm+DBdbFzGU/pqU2BLA++tlvjdiIUxCjquYIrcSyQtfU//KWa91hfOdaUhS5pOj4Cjnv5AKySty7zgsY191wDMwLaQ4MgjgbseKCCd5TivsBTzK6XFeEqDf30reBeNxjxMygHtFoNVK+WhYC1hJm24FwHN/ttv7vX1jet7CmHpJtFwR/bWn/l7VXQu736Xm2htE+ERZRgpiAm8Tsc8MDE2p7X0/az+EjlfagxQif3ZG/n54CqypHnKwWfi736A7+3miXGageTO3I9ImmD90nwRhzZ+VO25TUBacW3Hgd63bw3pUJq3FiL2QrEawFXXx7865o/3njGVVjvK7Hp5vg=
